language: go
go:
- '1.10'
before_install:
- go get -t -v ./...
script:
- go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
- CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w" -tags netgo -a -o "snogo" ./cmd/snogo/
- chmod +x snogo
- tar czvf "snogo-$TRAVIS_TAG.linux-amd64.tar.gz" snogo
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Xk8L7RLvIEbe8wjdaLUU5E8RyNtbakJyjh9DcMG2Oc7I9Dz8Ug0GvhBhr+4I+AEksnaDPDkUJBtdpGjSVIbQ5+aJzLe9iIQEhGbCqvd3aKsdkTtW8cC5QQiiZWh1bPwM3LymBNtQgowgqkbngvq7AaM9g1+7ynnKRhvka0SjFZiy6HvwwOAaC2zfowapTpd64lioe09SZDLMI9DqNR1/Qtbu7U55LMdfpEuTvMamr+4Gg5e1xMLknEyZYoRwpwlnEvUM83wRn7gSYUVEozg6frWSW+yMVDWwWgsyqJrI1OCwz/Nj3W4vEOv/tqIzemlkmVF4CpFH9+d0MTwe2ONlt0UzCsdSBRf9VmVhVWmA7C85tulmWRRHcQPTN3h+dEK71fRs7vQUm7/7aGNBmuiUIerNePzoJrdeLwpKNE7Z6jSlAA7WFXOor7Ildki810xetkSaqPDuav0zZsmCV/G+A9Af9z+LdfinLSHeJWg2GDay37boeMrhs6oRvqKmkIPnUaNlHfjdUirhEczSBx1fmaBXk7ud6kjAUVZGVqDyAnFSyd5qfJI0AP8y1agZnPFMuGe0EtmOD3s2Mi1G9KbiSqa0FCu/FhIx+G34BX+PC6TmIT4C8QAfahGf3zs859IIX0Dt6kKaQdfnGVbdH6/DjYx4LussqafxTX5HXsiqzno=
  file: snogo-$TRAVIS_TAG.linux-amd64.tar.gz
  on:
    repo: HealthPartners/snogo
    tags: true
    branch: master

